---
- name: Powershellスクリプト配置
  win_copy:
    src: "{{ CPF_Set_IPaddr }}"
    dest: "{{ GBL_POWERSHELLPATH }}\\{{ CPF_Set_IPaddr | basename }}"
  when: _target_list | length > 0


- name: IPアドレス設定(DHCP)
  win_shell: |
    . {{ GBL_POWERSHELLPATH }}\\{{ CPF_Set_IPaddr | basename }} ; Set-VMNetworkConfiguration `
    -Dhcp `
    -NetworkAdapter $(VMNetworkAdapter {{ item.0 }})
  register: set_ip_result
  failed_when: not set_ip_result.stderr == ""
  when: item.1
  loop: "{{ _target_list }}"


- name: IPアドレス設定(Static)
  win_shell: |
    . {{ GBL_POWERSHELLPATH }}\\{{ CPF_Set_IPaddr | basename }} ; Set-VMNetworkConfiguration `
    $(VMNetworkAdapter {{ item.0 }}) `
    {{ item.2 }} `
    {{ item.3 }} `
    {{ item.4 }} `
    {{ item.5 }}
  register: set_ip_result
  failed_when: not set_ip_result.stderr == ""
  when: not item.1
  loop: "{{ _target_list }}"
