---
- name: 作業対象入れを用意
  set_fact:
    _target_list: []


- name: 処理状況が「追加」または「起動済」のレコードを抽出
  set_fact:
    _target_list: "{{ _target_list + [[ item.1, item.2, item.3 ]] }}"
  when: item.0 == "追加" or item.0 == "起動済" and item.1
  with_together:
    - "{{ VAR_VMFlag }}"
    - "{{ VAR_VMName }}"
    - "{{ VAR_USERName }}"
    - "{{ VAR_USERPassword }}"


- name: 作業対象が存在しない場合終了
  fail:
    msg: "作業対象となるレコードが存在しません。"
  when: _target_list | length <= 0
